# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87b2ceff5b28ed9a2cc4a5f0cdf42ba4d2a89ca1de85380ba248e534c262855352e9ca912859a48537125c06e7ddd1add47117ab5d2e47dba68404e5757a7224

test:
  secret_key_base: f53772d6d393cfee3e407c05831a0dffb02a21d05a7cb60c5d5b86be9947c8357bd56e810c79733a2d3c3c95f53a6b928375e5e2bbaa8133d280cfbe3d8027e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
